# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-29 13:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('category_one', models.CharField(blank=True, choices=[('appliances', 'Appliances'), ('electronic_equipment', 'Electronic Equipment'), ('furniture', 'Furniture'), ('it_equipment', 'IT Equipment'), ('stationery', 'Stationery')], max_length=50, null=True, verbose_name='Category 1')),
                ('category_two', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category 2')),
                ('category_three', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category 3')),
                ('asset_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asset Description')),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial Number')),
                ('colour', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, choices=[('good', 'Good'), ('new', 'New'), ('poor', 'Poor')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('in_use', 'In Use'), ('in_storage', 'In Storage')], max_length=50, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier Name')),
                ('warranty_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Warranty Expiry')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, choices=[('administration', 'Administration'), ('client_services', 'Client Services'), ('finance', 'Finance'), ('human_resources', 'Human Resources'), ('it', 'IT'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('sales', 'Sales')], max_length=50, null=True)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetPurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice Number')),
                ('purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='Purchase Date')),
                ('asset_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Purchase Price')),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VAT')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Price')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAsset',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('category_one', models.CharField(blank=True, choices=[('appliances', 'Appliances'), ('electronic_equipment', 'Electronic Equipment'), ('furniture', 'Furniture'), ('it_equipment', 'IT Equipment'), ('stationery', 'Stationery')], max_length=50, null=True, verbose_name='Category 1')),
                ('category_two', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category 2')),
                ('category_three', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category 3')),
                ('asset_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asset Description')),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial Number')),
                ('colour', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, choices=[('good', 'Good'), ('new', 'New'), ('poor', 'Poor')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('in_use', 'In Use'), ('in_storage', 'In Storage')], max_length=50, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Supplier Name')),
                ('warranty_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Warranty Expiry')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical asset',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAssetDetail',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, choices=[('administration', 'Administration'), ('client_services', 'Client Services'), ('finance', 'Finance'), ('human_resources', 'Human Resources'), ('it', 'IT'), ('marketing', 'Marketing'), ('operations', 'Operations'), ('sales', 'Sales')], max_length=50, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical asset detail',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAssetPurchaseDetail',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Invoice Number')),
                ('purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='Purchase Date')),
                ('asset_purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Purchase Price')),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='VAT')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Price')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical asset purchase detail',
            },
        ),
    ]
