# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0002_auto_20171206_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledocument',
            name='document_type',
            field=models.CharField(choices=[(b'invoice', b'Invoice'), (b'lease', b'Lease Agreement'), (b'contract', b'Contract'), (b'natis', b'Natis Document'), (b'quotation', b'Quotation'), (b'other', b'Other')], default=b'other', max_length=255),
        ),
    ]
