# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0003_auto_20171218_0022'),
        ('fleet_management', '0006_auto_20171220_1613'),
    ]

    operations = [
    ]
