# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 08:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0007_merge_20180103_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branding',
            name='installation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Installation Date'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='installer_name',
            field=models.CharField(max_length=255, verbose_name=b'Installer Name'),
        ),
        migrations.AlterField(
            model_name='branding',
            name='supplier_name',
            field=models.CharField(max_length=255, verbose_name=b'Supplier Name'),
        ),
        migrations.AlterField(
            model_name='financedetail',
            name='contract_number',
            field=models.CharField(max_length=255, verbose_name=b'Contract Number'),
        ),
        migrations.AlterField(
            model_name='financedetail',
            name='contract_term_months',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Contract Term Months'),
        ),
        migrations.AlterField(
            model_name='financedetail',
            name='settlement_amount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Settlement Amount'),
        ),
        migrations.AlterField(
            model_name='financedetail',
            name='settlement_amount_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Settlement Amount Date'),
        ),
        migrations.AlterField(
            model_name='historicalbranding',
            name='installation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Installation Date'),
        ),
        migrations.AlterField(
            model_name='historicalbranding',
            name='installer_name',
            field=models.CharField(max_length=255, verbose_name=b'Installer Name'),
        ),
        migrations.AlterField(
            model_name='historicalbranding',
            name='supplier_name',
            field=models.CharField(max_length=255, verbose_name=b'Supplier Name'),
        ),
        migrations.AlterField(
            model_name='historicalfinancedetail',
            name='contract_number',
            field=models.CharField(max_length=255, verbose_name=b'Contract Number'),
        ),
        migrations.AlterField(
            model_name='historicalfinancedetail',
            name='contract_term_months',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Contract Term Months'),
        ),
        migrations.AlterField(
            model_name='historicalfinancedetail',
            name='settlement_amount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Settlement Amount'),
        ),
        migrations.AlterField(
            model_name='historicalfinancedetail',
            name='settlement_amount_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Settlement Amount Date'),
        ),
        migrations.AlterField(
            model_name='historicalinsurance',
            name='broker_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Broker Name'),
        ),
        migrations.AlterField(
            model_name='historicalinsurance',
            name='insurance_type',
            field=models.CharField(choices=[(b'insurance', b'Insurance'), (b'shortfall', b'Shortfall Cover')], default=b'insurance', max_length=255, verbose_name=b'Insurance Type'),
        ),
        migrations.AlterField(
            model_name='historicalinsurance',
            name='insured_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Insured Amount'),
        ),
        migrations.AlterField(
            model_name='historicalpurchasedetail',
            name='invoice_number',
            field=models.CharField(max_length=255, verbose_name=b'Invoice Number'),
        ),
        migrations.AlterField(
            model_name='historicalpurchasedetail',
            name='purchase_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Purchase Amount'),
        ),
        migrations.AlterField(
            model_name='historicalpurchasedetail',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Purchase Date'),
        ),
        migrations.AlterField(
            model_name='historicalpurchasedetail',
            name='purchase_type',
            field=models.CharField(choices=[(b'cash', b'Cash'), (b'hp', b'HP - Hire Purchase'), (b'lease', b'Lease'), (b'rental', b'Rental')], max_length=50, verbose_name=b'Purchase Type'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='delivery_mileage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Delivery Mileage'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='engine_capacity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Engine Capacity'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='engine_number',
            field=models.CharField(max_length=255, verbose_name=b'Engine Number'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='fuel_type',
            field=models.CharField(choices=[(b'petrol', b'Petrol'), (b'diesel', b'Diesel')], default=b'petrol', max_length=120, verbose_name=b'Fuel Type'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='has_aircon',
            field=models.NullBooleanField(verbose_name=b'Has Aircon'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='has_bluetooth',
            field=models.NullBooleanField(verbose_name=b'Has Bluetooth'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='has_jack',
            field=models.NullBooleanField(verbose_name=b'Has Jack'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='has_radio',
            field=models.NullBooleanField(verbose_name=b'Has Radio'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='has_spanner',
            field=models.NullBooleanField(verbose_name=b'Has Spanner'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='has_triangle',
            field=models.NullBooleanField(verbose_name=b'Has Triangle'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='licence_disk_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'License Disk Expiry'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Registration Date'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='registration_number',
            field=models.CharField(max_length=255, verbose_name=b'Registration Number'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='status_at_create',
            field=models.CharField(choices=[(b'new', b'New'), (b'used', b'Used')], default=b'new', max_length=50, verbose_name=b'Status at Create'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='tank_capacity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Tank Capacity'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='vin_number',
            field=models.CharField(max_length=255, verbose_name=b'Vin Number'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='year_model',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Year Model'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='broker_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Broker Name'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_type',
            field=models.CharField(choices=[(b'insurance', b'Insurance'), (b'shortfall', b'Shortfall Cover')], default=b'insurance', max_length=255, verbose_name=b'Insurance Type'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insured_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Insured Amount'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='invoice_number',
            field=models.CharField(max_length=255, verbose_name=b'Invoice Number'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase_amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Purchase Amount'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Purchase Date'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase_type',
            field=models.CharField(choices=[(b'cash', b'Cash'), (b'hp', b'HP - Hire Purchase'), (b'lease', b'Lease'), (b'rental', b'Rental')], max_length=50, verbose_name=b'Purchase Type'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='contract_term_months',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Contract Term Months'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='dealership_name',
            field=models.CharField(max_length=255, verbose_name=b'Dealership Name'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='installation_date',
            field=models.DateTimeField(verbose_name=b'Installation Date'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='installation_type',
            field=models.CharField(choices=[(b'new', b'New'), (b'reinstall', b'Re-Install')], default=b'new', max_length=255, verbose_name=b'Installation Type'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='previous_vehicle_reg_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Previous Vehicle Reg Number'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='purchase_type',
            field=models.CharField(choices=[(b'cash', b'Cash'), (b'rental', b'Rental')], default=b'cash', max_length=255, verbose_name=b'Purchase Type'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='settlement_amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Settlement Amount'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='settlement_amount_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Settlement Amount Date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='delivery_mileage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Delivery Mileage'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_capacity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Engine Capacity'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(max_length=255, verbose_name=b'Engine Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[(b'petrol', b'Petrol'), (b'diesel', b'Diesel')], default=b'petrol', max_length=120, verbose_name=b'Fuel Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_aircon',
            field=models.NullBooleanField(verbose_name=b'Has Aircon'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_bluetooth',
            field=models.NullBooleanField(verbose_name=b'Has Bluetooth'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_jack',
            field=models.NullBooleanField(verbose_name=b'Has Jack'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_radio',
            field=models.NullBooleanField(verbose_name=b'Has Radio'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_spanner',
            field=models.NullBooleanField(verbose_name=b'Has Spanner'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_triangle',
            field=models.NullBooleanField(verbose_name=b'Has Triangle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='licence_disk_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'License Disk Expiry'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Registration Date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=255, verbose_name=b'Registration Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status_at_create',
            field=models.CharField(choices=[(b'new', b'New'), (b'used', b'Used')], default=b'new', max_length=50, verbose_name=b'Status at Create'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tank_capacity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Tank Capacity'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin_number',
            field=models.CharField(max_length=255, verbose_name=b'Vin Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_model',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Year Model'),
        ),
    ]
