# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0008_auto_20180104_1009'),
        ('fleet_management', '0008_auto_20180105_1031'),
    ]

    operations = [
    ]
