# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 09:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20180105_1031'),
        ('fleet_management', '0009_auto_20180108_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='driver',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incident_driver', to='employees.Employee'),
        ),
    ]
