# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 09:11
from __future__ import unicode_literals
from django.db import migrations

from fleet_management.models import Incident

class Migration(migrations.Migration):

    def assign_incident_driver(apps, schema_editor):
        incidents = Incident.objects.all()

        for incident in incidents:            
            incident.driver = incident.vehicle_driver.driver
            
    dependencies = [
        ('fleet_management', '0010_incident_driver'),
    ]

    operations = [
        #migrations.RunPython(assign_incident_driver), #Redo migrations
    ]
