# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0011_auto_20180109_1111'),
        ('fleet_management', '0009_merge_20180108_1611'),
    ]

    operations = [
    ]
