# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 11:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0012_merge_20180110_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcard',
            name='card_number',
            field=models.CharField(max_length=255, verbose_name=b'Card Number'),
        ),
        migrations.AlterField(
            model_name='fuelcard',
            name='card_type',
            field=models.CharField(choices=[(b'fuel', b'Fuel Only'), (b'fuel oil', b'Fuel & Oil'), (b'fuel oil toll', b'Fuel, Oil & Toll'), (b'fuel oil etag', b'Fuel, Oil & eTag')], max_length=255, verbose_name=b'Card Type'),
        ),
        migrations.AlterField(
            model_name='historicalfuelcard',
            name='card_number',
            field=models.CharField(max_length=255, verbose_name=b'Card Number'),
        ),
        migrations.AlterField(
            model_name='historicalfuelcard',
            name='card_type',
            field=models.CharField(choices=[(b'fuel', b'Fuel Only'), (b'fuel oil', b'Fuel & Oil'), (b'fuel oil toll', b'Fuel, Oil & Toll'), (b'fuel oil etag', b'Fuel, Oil & eTag')], max_length=255, verbose_name=b'Card Type'),
        ),
        migrations.AlterField(
            model_name='historicalinsurance',
            name='insurance_type',
            field=models.CharField(choices=[(b'insurance', b'Insurance'), (b'shortfall', b'Shortfall Cover')], max_length=255, verbose_name=b'Insurance Type'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='division',
            field=models.CharField(choices=[(b'all', b'All'), (b'sales', b'Sales'), (b'marketing', b'Marketing')], max_length=120),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='fuel_type',
            field=models.CharField(choices=[(b'diesel', b'Diesel'), (b'petrol', b'Petrol')], max_length=120, verbose_name=b'Fuel Type'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='ownership',
            field=models.CharField(choices=[(b'emerald', b'Emerald'), (b'private', b'Private')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='status_at_create',
            field=models.CharField(choices=[(b'new', b'New'), (b'used', b'Used')], max_length=50, verbose_name=b'Status at Create'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='transmission',
            field=models.CharField(choices=[(b'automatic', b'Automatic'), (b'manual', b'Manual')], max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalvehiclemaintenance',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'End Date'),
        ),
        migrations.AlterField(
            model_name='historicalvehiclemaintenance',
            name='end_mileage',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'End Mileage'),
        ),
        migrations.AlterField(
            model_name='historicalvehiclemaintenance',
            name='plan_type',
            field=models.CharField(choices=[(b'maintenance_plan', b'Maintenance Plan'), (b'service_plan', b'Service Plan'), (b'warranty', b'Warranty')], max_length=50, verbose_name=b'Plan Type'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[(b'road accident', b'Road Accident'), (b'smash and grab', b'Smash And Grab'), (b'tracker warning', b'Tracker Warning'), (b'traffic fine', b'Traffic Fine'), (b'vehicle theft', b'Vehicle Theft'), (b'windscreen', b'Windscreen')], max_length=255, verbose_name=b'Incident Type'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_type',
            field=models.CharField(choices=[(b'insurance', b'Insurance'), (b'shortfall', b'Shortfall Cover')], max_length=255, verbose_name=b'Insurance Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='division',
            field=models.CharField(choices=[(b'all', b'All'), (b'sales', b'Sales'), (b'marketing', b'Marketing')], max_length=120),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[(b'diesel', b'Diesel'), (b'petrol', b'Petrol')], max_length=120, verbose_name=b'Fuel Type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ownership',
            field=models.CharField(choices=[(b'emerald', b'Emerald'), (b'private', b'Private')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status_at_create',
            field=models.CharField(choices=[(b'new', b'New'), (b'used', b'Used')], max_length=50, verbose_name=b'Status at Create'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[(b'automatic', b'Automatic'), (b'manual', b'Manual')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='document_type',
            field=models.CharField(choices=[(b'', b'--------'), (b'contract', b'Contract'), (b'invoice', b'Invoice'), (b'lease', b'Lease Agreement'), (b'natis', b'Natis Document'), (b'quotation', b'Quotation'), (b'other', b'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'End Date'),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='end_mileage',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'End Mileage'),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='plan_type',
            field=models.CharField(choices=[(b'maintenance_plan', b'Maintenance Plan'), (b'service_plan', b'Service Plan'), (b'warranty', b'Warranty')], max_length=50, verbose_name=b'Plan Type'),
        ),
    ]
