# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0013_auto_20180110_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='division',
            field=models.CharField(choices=[(b'all', b'All'), (b'marketing', b'Marketing'), (b'sales', b'Sales')], max_length=120),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateTimeField(verbose_name=b'Incident Date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='division',
            field=models.CharField(choices=[(b'all', b'All'), (b'marketing', b'Marketing'), (b'sales', b'Sales')], max_length=120),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='document_type',
            field=models.CharField(choices=[(b'contract', b'Contract'), (b'invoice', b'Invoice'), (b'lease', b'Lease Agreement'), (b'natis', b'Natis Document'), (b'quotation', b'Quotation'), (b'other', b'Other')], max_length=255),
        ),
    ]
