# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0013_auto_20180110_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='division',
            field=models.CharField(choices=[(b'all', b'All'), (b'marketing', b'Marketing'), (b'sales', b'Sales')], max_length=120),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_date',
            field=models.DateTimeField(verbose_name=b'Incident Date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='division',
            field=models.CharField(choices=[(b'all', b'All'), (b'marketing', b'Marketing'), (b'sales', b'Sales')], max_length=120),
        ),
    ]
