# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0014_auto_20180118_1623'),
        ('fleet_management', '0015_merge_20180122_0848'),
    ]

    operations = [
    ]
