# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0016_merge_20180122_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='description',
            field=models.TextField(),
        ),
    ]
