# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0017_auto_20180122_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehiclemaintenance',
            name='plan_type',
            field=models.CharField(choices=[(b'maintenance plan', b'Maintenance Plan'), (b'service plan', b'Service Plan'), (b'warranty', b'Warranty')], max_length=50, verbose_name=b'Plan Type'),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='plan_type',
            field=models.CharField(choices=[(b'maintenance plan', b'Maintenance Plan'), (b'service plan', b'Service Plan'), (b'warranty', b'Warranty')], max_length=50, verbose_name=b'Plan Type'),
        ),
    ]
