# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0019_auto_20180124_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcard',
            name='card_type',
            field=models.CharField(choices=[(b'fuel', b'Fuel Only'), (b'fuel oil', b'Fuel & Oil'), (b'fuel oil toll', b'Fuel, Oil & Toll'), (b'fuel oil etag', b'Fuel, Oil & eTag')], max_length=255, verbose_name=b'Card Type'),
        ),
        migrations.AlterField(
            model_name='historicalfuelcard',
            name='card_type',
            field=models.CharField(choices=[(b'fuel', b'Fuel Only'), (b'fuel oil', b'Fuel & Oil'), (b'fuel oil toll', b'Fuel, Oil & Toll'), (b'fuel oil etag', b'Fuel, Oil & eTag')], max_length=255, verbose_name=b'Card Type'),
        ),
        migrations.AlterField(
            model_name='historicalvehiclemaintenance',
            name='service_interval',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Service Interval'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='vehicle_driver',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incident', to='fleet_management.VehicleDriver'),
        ),
        migrations.AlterField(
            model_name='vehiclemaintenance',
            name='service_interval',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'Service Interval'),
        ),
    ]
