# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet_management', '0023_auto_20180205_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('date_of_service', models.DateTimeField(verbose_name=b'Date Of Service')),
                ('comment', models.TextField()),
                ('created_by', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_bookings', to=settings.AUTH_USER_MODEL)),
                ('modified_by', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_service_bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_bookings', to='fleet_management.Vehicle')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
