# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 09:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_auto_20180206_1336'),
        ('fleet_management', '0024_servicebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='date_of_service',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='address',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_booking_address', to='operations.Address'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Booking Date'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='contact_person',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_booking_contact_person', to='operations.Contact'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='current_mileage',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Current Mileage'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='plan_type',
            field=models.CharField(choices=[(b'maintenance plan', b'Maintenance Plan'), (b'service plan', b'Service Plan'), (b'warranty', b'Warranty')], default=django.utils.timezone.now, max_length=50, verbose_name=b'Plan Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='qoute_amount',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Qoute Amount'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='qoute_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Qoute Date'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='qoute_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Qoute Number'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='qoute_reason',
            field=models.TextField(blank=True, null=True, verbose_name=b'Reason'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='quote_received',
            field=models.CharField(choices=[(b'', b'--- Select Answer ---'), (b'yes', b'Yes'), (b'no', b'No')], default=django.utils.timezone.now, max_length=50, verbose_name=b'Quote Received'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Service Date'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_interval',
            field=models.CharField(blank=True, choices=[(b'10000', b'10 000km'), (b'15000', b'15 000km'), (b'20000', b'20 000km'), (b'30000', b'30 000km'), (b'40000', b'40 000km'), (b'45000', b'45 000km'), (b'50000', b'50 000km'), (b'60000', b'60 000km'), (b'70000', b'70 000km'), (b'75000', b'75 000km'), (b'80000', b'80 000km'), (b'90000', b'90 000km'), (b'100000', b'100 000km')], max_length=255, null=True, verbose_name=b'Service Interval'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_provider',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name=b'Service Provider'),
            preserve_default=False,
        ),
    ]
