# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 09:29
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0025_auto_20180219_1118'),
        ('operations', '0011_serviceprovider'),
        
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='address',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_bookings_address', to='operations.Address'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='contact_person',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_bookings_contact_person', to='operations.Contact'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_provider',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_bookings_service_provider', to='operations.ServiceProvider'),
        ),
    ]
