# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 13:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_vendor'),
        ('fleet_management', '0027_auto_20180222_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branding',
            name='installer_address',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='installer_contact_person',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='installer_name',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='supplier_address',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='supplier_contact_person',
        ),
        migrations.RemoveField(
            model_name='branding',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='historicalbranding',
            name='installer_address',
        ),
        migrations.RemoveField(
            model_name='historicalbranding',
            name='installer_contact_person',
        ),
        migrations.RemoveField(
            model_name='historicalbranding',
            name='installer_name',
        ),
        migrations.RemoveField(
            model_name='historicalbranding',
            name='supplier_address',
        ),
        migrations.RemoveField(
            model_name='historicalbranding',
            name='supplier_contact_person',
        ),
        migrations.RemoveField(
            model_name='historicalbranding',
            name='supplier_name',
        ),
        migrations.RemoveField(
            model_name='historicalinsurance',
            name='insurer',
        ),
        migrations.RemoveField(
            model_name='historicalpurchasedetail',
            name='dealership',
        ),
        migrations.RemoveField(
            model_name='historicalpurchasedetail',
            name='dealership_address',
        ),
        migrations.RemoveField(
            model_name='historicalpurchasedetail',
            name='dealership_contact_person',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='insurer',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='dealership',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='dealership_address',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='dealership_contact_person',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='dealership_name',
        ),
        migrations.AddField(
            model_name='branding',
            name='installer',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branding_installer', to='operations.Vendor'),
        ),
        migrations.AddField(
            model_name='branding',
            name='supplier',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branding_supplier', to='operations.Vendor'),
        ),
        migrations.AddField(
            model_name='historicalbranding',
            name='installer',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.Vendor'),
        ),
        migrations.AddField(
            model_name='historicalbranding',
            name='supplier',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.Vendor'),
        ),
        migrations.AddField(
            model_name='historicalinsurance',
            name='vendor',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.Vendor'),
        ),
        migrations.AddField(
            model_name='historicalpurchasedetail',
            name='vendor',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.Vendor'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='vendor',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_insurer', to='operations.Vendor'),
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='vendor',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_details_dealer', to='operations.Vendor'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='vendor',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_bookings_vendor', to='operations.Vendor'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='vendor',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Tracker_tracker', to='operations.Vendor'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='vehicle',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_vehicle', to='fleet_management.Vehicle'),
        ),
    ]
