# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0028_auto_20180308_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledriver',
            name='reason',
            field=models.CharField(choices=[(b'dismissed', b'Dismissed'), (b'new employee', b'New Employee'), (b'resignation', b'Resignation'), (b'suspend', b'Suspend'), (b'temp vehicle', b'Temp Vehicle'), (b'other', b'Other')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
