# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 13:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0029_vehicledriver_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='qoute_amount',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Quote Amount'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='qoute_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Quote Date'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='qoute_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Quote Number'),
        ),
    ]
