# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 12:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0030_auto_20180320_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='service_interval',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Service Interval'),
        ),
        migrations.AlterField(
            model_name='vehicledriver',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'End Date'),
        ),
    ]
