# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-14 14:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0032_auto_20180514_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='qoute_amount',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='qoute_date',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='qoute_number',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='qoute_reason',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='quote_received',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='document_amount',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Document Amount'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='document_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Document Date'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Document Number'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='document_received',
            field=models.CharField(choices=[(b'', b'--- Select Answer ---'), (b'Invoice', b'Invoice'), (b'Quote', b'Quote')], default=None, max_length=50, verbose_name=b'Document Received'),
            preserve_default=False,
        ),
    ]
