# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0035_auto_20180516_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcardusage',
            name='usage_type',
            field=models.CharField(choices=[(b'import', b'Import'), (b'manual', b'Manual')], default=b'import', max_length=255),
        ),
    ]
