# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-22 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_auto_20180517_1217'),
        ('fleet_management', '0035_auto_20180516_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcard',
            name='vendor',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_card_supplier', to='operations.Vendor'),
        ),
        migrations.AddField(
            model_name='historicalfuelcard',
            name='vendor',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.Vendor'),
        ),
        migrations.AlterField(
            model_name='fuelcard',
            name='card_number',
            field=models.CharField(max_length=255, unique=True, verbose_name=b'Card Number'),
        ),
        migrations.AlterField(
            model_name='historicalfuelcard',
            name='card_number',
            field=models.CharField(db_index=True, max_length=255, verbose_name=b'Card Number'),
        ),
    ]
