# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0036_auto_20180522_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('make_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('model_name', models.CharField(max_length=255, unique=True)),
                ('make', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_make', to='fleet_management.VehicleMake')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='has_aircon',
            field=models.NullBooleanField(verbose_name=b'Aircon'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='has_bluetooth',
            field=models.NullBooleanField(verbose_name=b'Bluetooth'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='has_jack',
            field=models.NullBooleanField(verbose_name=b'Jack'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='has_radio',
            field=models.NullBooleanField(verbose_name=b'Radio'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='has_spanner',
            field=models.NullBooleanField(verbose_name=b'Spanner'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='has_triangle',
            field=models.NullBooleanField(verbose_name=b'Triangle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_aircon',
            field=models.NullBooleanField(verbose_name=b'Aircon'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_bluetooth',
            field=models.NullBooleanField(verbose_name=b'Bluetooth'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_jack',
            field=models.NullBooleanField(verbose_name=b'Jack'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_radio',
            field=models.NullBooleanField(verbose_name=b'Radio'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_spanner',
            field=models.NullBooleanField(verbose_name=b'Spanner'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='has_triangle',
            field=models.NullBooleanField(verbose_name=b'Triangle'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='vehicle_make',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet_management.VehicleMake'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='vehicle_model',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet_management.VehicleModel'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_make',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_make', to='fleet_management.VehicleMake', verbose_name=b'Make'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_model', to='fleet_management.VehicleModel', verbose_name=b'Model'),
        ),
    ]
