# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0036_fuelcardusage_usage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcardusage',
            name='transaction_type',
            field=models.CharField(choices=[(b'FUEL', b'FUEL'), (b'OIL', b'OIL'), (b'MAINTENANCE', b'MAINTENANCE'), (b'TOLL-GATE', b'TOLL-GATE'), (b'CARD FEE', b'CARD FEE'), (b'DAMAGED CRD_FEE', b'DAMAGED CRD_FEE'), (b'TRANSACTION FEE', b'TRANSACTION FEE'), (b'COURIER SERVICE', b'COURIER SERVICE'), (b'VAT OF SER FEES', b'VAT OF SER FEES')], default=b'FUEL', max_length=255),
        ),
    ]
