# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 11:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0038_auto_20180525_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='service_interval',
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='service_interval',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Service Interval'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_interval',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Service Interval'),
        ),
    ]
