# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0039_auto_20180529_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledriver',
            name='reason',
            field=models.CharField(choices=[(b'dismissed', b'Dismissed'), (b'new employee', b'New Employee'), (b'resignation', b'Resignation'), (b'suspend', b'Suspend'), (b'temp vehicle', b'Temp Vehicle'), (b'uncontactable', b'Uncontactable'), (b'other', b'Other')], max_length=255),
        ),
    ]
