# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0040_auto_20180531_1225'),
        ('fleet_management', '0041_auto_20180530_2158'),
    ]

    operations = [
    ]
