# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0042_merge_20180605_1446'),
        ('fleet_management', '0040_auto_20180601_1633'),
    ]

    operations = [
    ]
