# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-05 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0045_auto_20180605_1501'),
        ('fleet_management', '0042_merge_20180605_1445'),
    ]

    operations = [
    ]
