# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0046_merge_20180605_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledriver',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
