# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0046_merge_20180605_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Reference Number'),
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(blank=True, choices=[(b'captured', b'Captured'), (b'paid', b'Paid'), (b'rejected', b'Rejected'), (b'submitted for payment', b'Submit For Payment')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
