# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0047_auto_20180608_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentDocumentUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('description', models.CharField(max_length=255)),
                ('incident_type', models.CharField(max_length=255)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='incidentdocument',
            name='upload',
        ),
        migrations.AddField(
            model_name='incidentdocument',
            name='upload',
            field=models.ManyToManyField(to='fleet_management.IncidentDocumentUploads'),
        ),
    ]
