# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0047_auto_20180606_1642'),
        ('fleet_management', '0037_fuelcardusage_transaction_type'),
    ]

    operations = [
    ]
