# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 11:59
from __future__ import unicode_literals

from django.db import migrations
from fleet_management.models import IncidentDocumentUploads
def populate_upload_types(apps, schema_editor):
	upload = IncidentDocumentUploads.objects.get_or_create(incident_type="Traffic Fine", description="Traffic Fine")
	upload = IncidentDocumentUploads.objects.get_or_create(incident_type="", description="Requisition")
	upload = IncidentDocumentUploads.objects.get_or_create(incident_type="", description="Proof Of Payment")
	upload = IncidentDocumentUploads.objects.get_or_create(incident_type="Incident", description="Quote")

class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0048_auto_20180611_1356'),
    ]

    operations = [
    	migrations.RunPython(populate_upload_types)
    ]
