# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0049_auto_20180611_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentdocument',
            old_name='upload',
            new_name='document_type',
        ),
    ]
