# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0050_auto_20180612_1055'),
        ('fleet_management', '0048_merge_20180613_0929'),
    ]

    operations = [
    ]
