# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 07:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet_management', '0051_merge_20180614_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleFuelCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('start_date', models.DateTimeField(verbose_name=b'Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name=b'End Date')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vehiclefuelcard', to=settings.AUTH_USER_MODEL)),
                ('fuel_card', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_card_vehicle', to='fleet_management.FuelCard')),
                ('modified_by', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_vehiclefuelcard', to=settings.AUTH_USER_MODEL)),
                ('vehicle', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_fuel_card', to='fleet_management.Vehicle')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
