# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 07:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_auto_20180517_1217'),
        ('fleet_management', '0051_merge_20180614_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='district',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.Branch'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='region',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.Region'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='district',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_district', to='operations.Branch'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='region',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_region', to='operations.Region'),
        ),
    ]
