# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0051_merge_20180614_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[(b'vehicle', b'Vehicle'), (b'windscreen', b'Windscreen')], max_length=255, verbose_name=b'Incident Type'),
        ),
        migrations.AlterField(
            model_name='incidentdocument',
            name='document_type',
            field=models.ManyToManyField(to='fleet_management.IncidentDocumentUploads', verbose_name=b'Document Type'),
        ),
    ]
