# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-22 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0052_auto_20180619_1556'),
        ('fleet_management', '0052_auto_20180620_0914'),
    ]

    operations = [
    ]
