# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0054_auto_20180626_1558'),
        ('fleet_management', '0053_merge_20180622_1429'),
    ]

    operations = [
    ]
