# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-02 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0055_merge_20180627_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelcard',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='fuelcard',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='historicalfuelcard',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='historicalfuelcard',
            name='vehicle',
        ),
    ]
