# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 08:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20180206_1327'),
        ('operations', '0017_auto_20180703_1347'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet_management', '0056_auto_20180702_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('incident_date', models.DateTimeField(verbose_name=b'Incident Date')),
                ('division', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Division')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Region')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'District')),
                ('ownership', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Ownership')),
                ('vin_number', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Vin Number')),
                ('engine_number', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Engine Number')),
                ('colour', models.CharField(blank=True, max_length=255, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('year_model', models.IntegerField(blank=True, null=True, verbose_name=b'Year Model')),
                ('claim_type', models.CharField(choices=[(b'', b'--- Select Answer ---'), (b'accident claim', b'Accident Claim'), (b'windscreen', b'Windscreen'), (b'vehicle theft', b'Vehicle Theft'), (b'other', b'Other')], max_length=50, verbose_name=b'Claim Type')),
                ('reason_other', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Reason')),
                ('quote_reference_number', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Quote Reference Number')),
                ('quote_amount', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Quote Amount')),
                ('damage_description', models.TextField()),
                ('incident_description', models.TextField()),
                ('submission_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Insurance Submission Date')),
                ('insurance_reference_number', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Reference Number')),
                ('insurance_date_recieved', models.DateTimeField(blank=True, null=True, verbose_name=b'Insurance Date Recieved')),
                ('insurance_comment', models.TextField(blank=True, null=True, verbose_name=b'Insurance Comment')),
                ('claim_number', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Claim Number')),
                ('claim_date_recieved', models.DateTimeField(blank=True, null=True, verbose_name=b'Claim Date Recieved')),
                ('claim_comment', models.TextField(blank=True, null=True, verbose_name=b'Claim Comment')),
                ('status', models.CharField(blank=True, choices=[(b'captured', b'Captured'), (b'paid', b'Paid'), (b'rejected', b'Rejected'), (b'submitted for payment', b'Submit For Payment')], max_length=255, null=True)),
                ('created_by', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_insurance_claims', to=settings.AUTH_USER_MODEL)),
                ('driver', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claim_driver', to='employees.Employee')),
                ('modified_by', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_insurance_claims', to=settings.AUTH_USER_MODEL)),
                ('vehicle', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_vehicle', to='fleet_management.Vehicle')),
                ('vendor', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claim_vendor', to='operations.Vendor')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaimDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_insurance_claim_documents', to=settings.AUTH_USER_MODEL)),
                ('document', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.Document')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaimDocumentUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('description', models.CharField(max_length=255)),
                ('insurance_claim_type', models.CharField(max_length=255)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='insuranceclaimdocument',
            name='document_type',
            field=models.ManyToManyField(to='fleet_management.InsuranceClaimDocumentUploads', verbose_name=b'Document Type'),
        ),
        migrations.AddField(
            model_name='insuranceclaimdocument',
            name='insurance_claim',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claim_documents', to='fleet_management.InsuranceClaim'),
        ),
        migrations.AddField(
            model_name='insuranceclaimdocument',
            name='modified_by',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_insurance_claim_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
