# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0056_auto_20180702_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcard',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Cancelled Date'),
        ),
        migrations.AddField(
            model_name='fuelcard',
            name='status',
            field=models.CharField(choices=[(b'active', b'Active'), (b'cancelled', b'Cancelled')], default=b'active', max_length=25, verbose_name=b'Status'),
        ),
        migrations.AddField(
            model_name='historicalfuelcard',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Cancelled Date'),
        ),
        migrations.AddField(
            model_name='historicalfuelcard',
            name='status',
            field=models.CharField(choices=[(b'active', b'Active'), (b'cancelled', b'Cancelled')], default=b'active', max_length=25, verbose_name=b'Status'),
        ),
    ]
