# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 13:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0057_auto_20180704_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcard',
            name='vehicle_assigned',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_fuealcard', to='fleet_management.Vehicle'),
        ),
        migrations.AddField(
            model_name='historicalfuelcard',
            name='vehicle_assigned',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet_management.Vehicle'),
        ),
    ]
