# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 11:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0057_auto_20180703_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='delivery_odometer_mileage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Delivery Odometer Mileage'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='delivery_odometer_mileage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Delivery Odometer Mileage'),
        ),
    ]
