# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0058_auto_20180705_1642'),
        ('fleet_management', '0058_auto_20180705_1314'),
    ]

    operations = [
    ]
