# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0058_auto_20180704_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcard',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Start Date'),
        ),
        migrations.AddField(
            model_name='historicalfuelcard',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Start Date'),
        ),
    ]
