# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0059_merge_20180709_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaim',
            name='damage_description',
            field=models.TextField(verbose_name=b'Damage Description'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='incident_description',
            field=models.TextField(verbose_name=b'Incident Description'),
        ),
    ]
