# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_auto_20180703_1347'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet_management', '0060_auto_20180709_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCardUsageDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_fuel_usage_documents', to=settings.AUTH_USER_MODEL)),
                ('document', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.Document')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuelCardUsageDocumentUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fuelcardusagedocument',
            name='document_type',
            field=models.ManyToManyField(to='fleet_management.FuelCardUsageDocumentUploads', verbose_name=b'Document Type'),
        ),
        migrations.AddField(
            model_name='fuelcardusagedocument',
            name='fuel_usage',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_usage_documents', to='fleet_management.FuelCardUsage'),
        ),
        migrations.AddField(
            model_name='fuelcardusagedocument',
            name='modified_by',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_fuel_usage_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
