# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0060_auto_20180710_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaimDocumentTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='insuranceclaimdocument',
            name='document_type',
            field=models.ManyToManyField(to='fleet_management.InsuranceClaimDocumentTypes', verbose_name=b'Document Type'),
        ),
    ]
