# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 13:25
from __future__ import unicode_literals

from django.db import migrations
from fleet_management.models import InsuranceClaimDocumentTypes
def populate_upload_types(apps, schema_editor):
	upload = InsuranceClaimDocumentTypes.objects.get_or_create(description="Affidavit")
	upload = InsuranceClaimDocumentTypes.objects.get_or_create(description="Police Report")
	upload = InsuranceClaimDocumentTypes.objects.get_or_create(description="Drivers Licence")
	upload = InsuranceClaimDocumentTypes.objects.get_or_create(description="Claim Form")
	upload = InsuranceClaimDocumentTypes.objects.get_or_create(description="Pictures of Damage")
	upload = InsuranceClaimDocumentTypes.objects.get_or_create(description="Quotation")
	upload = InsuranceClaimDocumentTypes.objects.get_or_create(description="Incident and Accident Report")

class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0061_auto_20180710_1514'),
    ]

    operations = [
    	migrations.RunPython(populate_upload_types)
    ]
