# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 13:41
from __future__ import unicode_literals

from django.db import migrations
from fleet_management.models import FuelCardUsageDocumentUploads

def populate_upload_types(apps, schema_editor):
	upload = FuelCardUsageDocumentUploads.objects.get_or_create(description="Fuel Slips")
	upload = FuelCardUsageDocumentUploads.objects.get_or_create(description="Proof Of Payment")

class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0061_auto_20180709_1413'),
    ]

    operations = [
    	migrations.RunPython(populate_upload_types)
    ]
