# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0059_merge_20180709_1407'),
        ('fleet_management', '0062_auto_20180709_1541'),
    ]

    operations = [
    ]
