# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-11 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0062_auto_20180710_1525'),
        ('fleet_management', '0063_merge_20180709_1616'),
    ]

    operations = [
    ]
