# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-16 11:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0064_merge_20180711_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date Accepted'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Accepted Location'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='delivery_odometer_mileage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Accepted Odometer Mileage'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Engine Number'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='rental_contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Rental Company Contact Person'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='returned_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Return Location'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='vin_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Vin Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date Accepted'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Accepted Location'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='delivery_odometer_mileage',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Accepted Odometer Mileage'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Engine Number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rental_contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Rental Company Contact Person'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='returned_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Return Location'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Vin Number'),
        ),
    ]
