# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-23 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0065_auto_20180720_0946'),
        ('fleet_management', '0065_auto_20180716_1301'),
        ('fleet_management', '0065_auto_20180716_1337'),
        ('fleet_management', '0065_auto_20180718_1159'),
    ]

    operations = [
    ]
