# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-24 08:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20180206_1327'),
        ('fleet_management', '0065_auto_20180716_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='deposit_driver',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='deposit_paid_by',
            field=models.CharField(blank=True, choices=[(b'emerald', b'Emerald'), (b'driver', b'Driver')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='deposit_paid_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date Deposit Paid'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='rental_deposit_amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Rental Deposit Amount'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deposit_driver',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_deposit', to='employees.Employee'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deposit_paid_by',
            field=models.CharField(blank=True, choices=[(b'emerald', b'Emerald'), (b'driver', b'Driver')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='deposit_paid_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date Deposit Paid'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rental_deposit_amount',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Rental Deposit Amount'),
        ),
    ]
