# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0067_auto_20180724_1003'),
        ('fleet_management', '0066_auto_20180724_1002'),
    ]

    operations = [
    ]
