# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0068_merge_20180726_0812'),
        ('fleet_management', '0068_auto_20180725_1147'),
    ]

    operations = [
    ]
