# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 08:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0068_merge_20180726_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcard',
            name='card_limit',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Card Limit'),
        ),
        migrations.AddField(
            model_name='fuelcard',
            name='card_limit_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Comment'),
        ),
        migrations.AddField(
            model_name='historicalfuelcard',
            name='card_limit',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Card Limit'),
        ),
        migrations.AddField(
            model_name='historicalfuelcard',
            name='card_limit_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Comment'),
        ),
    ]
