# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0069_merge_20180727_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='drivers_licence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Drivers Licence'),
        ),
        migrations.AddField(
            model_name='incident',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Expiry Date'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='drivers_licence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Drivers Licence'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Expiry Date'),
        ),
    ]
