# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-30 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0069_auto_20180730_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelcard',
            name='card_limit_comment',
        ),
        migrations.RemoveField(
            model_name='historicalfuelcard',
            name='card_limit_comment',
        ),
        migrations.AddField(
            model_name='fuelcardusage',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Comments'),
        ),
    ]
