# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0070_auto_20180727_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[(b'vehicle', b'Vehicle'), (b'windscreen', b'Windscreen'), (b'other', b'Other')], max_length=255, verbose_name=b'Incident Type'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name=b'Share Amount'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name=b'Share Amount'),
        ),
    ]
