# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-01 10:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0070_auto_20180730_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcardusagedocument',
            name='fuel_usage',
            field=lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_usage_documents', to='fleet_management.FuelCard'),
        ),
    ]
