# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0072_auto_20180802_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcard',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Comments'),
        ),
        migrations.AddField(
            model_name='historicalfuelcard',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Comments'),
        ),
    ]
