# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 07:36
from __future__ import unicode_literals

from django.db import migrations
from fleet_management.models import FuelCardUsageDocumentUploads

def populate_upload_types(apps, schema_editor):
	upload = FuelCardUsageDocumentUploads.objects.get_or_create(description="Card Limit Change")

class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0073_auto_20180802_0822'),
    ]

    operations = [
    	migrations.RunPython(populate_upload_types)
    ]
