# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0071_auto_20180802_0942'),
        ('fleet_management', '0074_auto_20180802_0936'),
    ]

    operations = [
    ]
