# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-03 07:19
from __future__ import unicode_literals

from django.db import migrations
from fleet_management.models import FuelCardDocumentUploads

def populate_upload_types(apps, schema_editor):
	upload = FuelCardDocumentUploads.objects.get_or_create(description="Card Limit Change")

class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0075_merge_20180802_1107'),
    ]

    operations = [
    	migrations.RunPython(populate_upload_types)
    ]
