# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0076_auto_20180803_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Follow-up Date'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='long_term_repairs',
            field=models.BooleanField(default=False, verbose_name=b'Long Term Repairs'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_interval',
            field=models.CharField(blank=True, choices=[(b'5000', b'5 000km'), (b'10000', b'10 000km'), (b'15000', b'15 000km'), (b'20000', b'20 000km'), (b'25000', b'25 000km'), (b'30000', b'30 000km'), (b'35000', b'35 000km'), (b'40000', b'40 000km'), (b'45000', b'45 000km'), (b'50000', b'50 000km'), (b'55000', b'55 000km'), (b'60000', b'60 000km'), (b'65000', b'65 000km'), (b'70000', b'70 000km'), (b'75000', b'75 000km'), (b'80000', b'80 000km'), (b'85000', b'85 000km'), (b'90000', b'90 000km'), (b'95000', b'95 000km'), (b'100000', b'100 000km')], max_length=255, null=True, verbose_name=b'Service Interval'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(blank=True, choices=[(b'booked', b'Booked'), (b'escalated', b'Escalated'), (b'awaiting authorisation', b'Awaiting Authorisation'), (b'authorised', b'Authorised'), (b'declined', b'Declined')], max_length=255, null=True),
        ),
    ]
