# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-10 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0076_auto_20180803_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='driver_co_payment',
            field=models.CharField(blank=True, choices=[(b'yes', b'Yes'), (b'no', b'No')], max_length=255, null=True, verbose_name=b'Driver Co Payment'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='driver_co_payment',
            field=models.CharField(blank=True, choices=[(b'yes', b'Yes'), (b'no', b'No')], max_length=255, null=True, verbose_name=b'Driver Co Payment'),
        ),
    ]
