# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-13 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0078_auto_20180810_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='drivers_licence',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='vehicle_driver',
        ),
    ]
