# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-15 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0080_incidentcomment_insuranceclaimcomment'),
        ('fleet_management', '0078_auto_20180810_1026'),
    ]

    operations = [
    ]
