# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-20 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0077_auto_20180815_1443'),
        ('fleet_management', '0081_merge_20180815_0924'),
    ]

    operations = [
    ]
