# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-20 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0082_merge_20180820_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelcardusage',
            old_name='date_used',
            new_name='transaction_date',
        ),
        migrations.AddField(
            model_name='fuelcardusage',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Merchant Name'),
        ),
        migrations.AddField(
            model_name='fuelcardusage',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fuelcardusage',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Transaction Code'),
        ),
        migrations.AddField(
            model_name='fuelcardusage',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Transaction Number'),
        ),
    ]
