# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-22 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0083_auto_20180820_1204'),
        ('fleet_management', '0082_merge_20180820_1516'),
    ]

    operations = [
    ]
