# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0020_auto_20180820_1211'),
        ('fleet_management', '0084_merge_20180822_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMaintanceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('created_by', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_maintenance_documents', to=settings.AUTH_USER_MODEL)),
                ('document', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.Document')),
                ('modified_by', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_service_maintenance_documents', to=settings.AUTH_USER_MODEL)),
                ('service_booking', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_booking_documents', to='fleet_management.ServiceBooking')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
