# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-03 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0085_auto_20180827_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[(b'vehicle', b'Vehicle'), (b'windscreen', b'Windscreen'), (b'tyres', b'Tyres'), (b'other', b'Other')], max_length=255, verbose_name=b'Incident Type'),
        ),
    ]
