# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-11 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0085_servicemaintancedocument'),
        ('fleet_management', '0086_auto_20180903_0946'),
    ]

    operations = [
    ]
