# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-14 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0087_merge_20180911_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcardusage',
            name='transaction_type',
            field=models.ManyToManyField(related_name='fuel_usage_transaction_types', to='fleet_management.FuelCardUsageTransactionType', verbose_name=b'Transaction Type'),
        ),
    ]
