# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-26 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0088_auto_20180914_1417'),
        ('fleet_management', '0088_auto_20180919_1509'),
    ]

    operations = [
    ]
