# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0089_merge_20180926_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclaim',
            name='claim_type',
            field=models.CharField(choices=[(b'accident claim', b'Accident Claim'), (b'vehicle theft', b'Vehicle Theft'), (b'windscreen', b'Windscreen'), (b'other', b'Other')], max_length=50, verbose_name=b'Claim Type'),
        ),
    ]
