# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-01 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20180720_0946'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet_management', '0089_merge_20180926_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVehicleDriver',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('start_date', models.DateTimeField(verbose_name=b'Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name=b'End Date')),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.Employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet_management.Vehicle')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical vehicle driver',
            },
        ),
        migrations.AddField(
            model_name='vehicledriver',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
