# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-30 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20180720_0946'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet_management', '0089_merge_20180926_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIncident',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('incident_date', models.DateTimeField(verbose_name=b'Incident Date')),
                ('incident_type', models.CharField(choices=[(b'vehicle', b'Vehicle'), (b'windscreen', b'Windscreen'), (b'tyres', b'Tyres'), (b'other', b'Other')], max_length=255, verbose_name=b'Incident Type')),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Reference Number')),
                ('resolved', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[(b'captured', b'Captured'), (b'paid', b'Paid'), (b'rejected', b'Rejected'), (b'submitted for payment', b'Submit For Payment')], max_length=255, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name=b'Invoice Amount')),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Invoice Number')),
                ('driver_co_payment', models.CharField(blank=True, choices=[(b'yes', b'Yes'), (b'no', b'No')], max_length=255, null=True, verbose_name=b'Driver Co Payment')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('share_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name=b'Share Amount')),
                ('date_recieved_by_fleet', models.DateTimeField(blank=True, null=True, verbose_name=b'Date Recieved By Finance')),
                ('date_sent_to_finance', models.DateTimeField(blank=True, null=True, verbose_name=b'Date Sent Through To Finance')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='employees.Employee')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vehicle', lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='fleet_management.Vehicle')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical incident',
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='date_recieved_by_fleet',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date Recieved By Finance'),
        ),
        migrations.AddField(
            model_name='incident',
            name='date_sent_to_finance',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date Sent Through To Finance'),
        ),
    ]
