# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-09 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet_management', '0089_merge_20180926_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='authorised_by',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorised_service_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='created_by',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_service_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='document_received',
            field=models.CharField(blank=True, choices=[(b'', b'--- Select Answer ---'), (b'Invoice', b'Invoice'), (b'Quote', b'Quote')], max_length=50, null=True, verbose_name=b'Document Received'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='service_interval',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Service Interval'),
        ),
    ]
