# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-01 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0090_auto_20181101_0914'),
        ('fleet_management', '0090_auto_20181031_1225'),
    ]

    operations = [
    ]
