# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-02 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0090_auto_20181030_0954'),
        ('fleet_management', '0090_auto_20181030_1059'),
        ('fleet_management', '0090_auto_20181030_1404'),
        ('fleet_management', '0090_auto_20181031_1225'),
        ('fleet_management', '0090_auto_20181030_1331'),
    ]

    operations = [
    ]
