# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-01 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0091_merge_20181101_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicledriver',
            name='unassign_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
