# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-02 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0091_merge_20181102_1127'),
        ('fleet_management', '0092_historicalvehicledriver_unassign_reason'),
    ]

    operations = [
    ]
