# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-07 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0094_auto_20181102_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalincident',
            name='date_recieved_by_fleet',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date Recieved By Fleet'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date_recieved_by_fleet',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date Recieved By Fleet'),
        ),
    ]
