# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-15 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0095_auto_20181107_1048'),
        ('fleet_management', '0090_auto_20181109_1214'),
    ]

    operations = [
    ]
