# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-16 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0096_merge_20181115_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='document_received',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Document Type'),
        ),
    ]
