# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-20 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0097_auto_20181116_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
