# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-04 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0097_auto_20181116_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='installation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Installation Date'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='installation_type',
            field=models.CharField(blank=True, choices=[(b'new', b'New'), (b'reinstall', b'Re-Install')], max_length=255, null=True, verbose_name=b'Installation Type'),
        ),
    ]
