# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-28 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0099_merge_20181207_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='emerald_life_branded',
            field=models.NullBooleanField(verbose_name=b'Emerald Life Branded'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='emerald_life_branded',
            field=models.NullBooleanField(verbose_name=b'Emerald Life Branded'),
        ),
    ]
