# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-28 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0099_merge_20181207_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='division',
            field=models.CharField(choices=[(b'manager', b'Manager'), (b'sales_manager', b'Sales Manager'), (b'pool_vehicle', b'Pool Vehicle')], max_length=120),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='division',
            field=models.CharField(choices=[(b'manager', b'Manager'), (b'sales_manager', b'Sales Manager'), (b'pool_vehicle', b'Pool Vehicle')], max_length=120),
        ),
    ]
