# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-28 12:30
from __future__ import unicode_literals

from django.db import migrations
from fleet_management.models import VehicleStatusType

def add_status_types(apps, schema_editor):
    st = VehicleStatusType.objects.get_or_create(description="Sold")

class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0099_merge_20181207_1012'),
    ]

    operations = [
    	migrations.RunPython(add_status_types)
    ]
