# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-30 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0100_auto_20190128_1506'),
        ('fleet_management', '0100_auto_20190128_1043'),
        ('fleet_management', '0100_auto_20190128_1430'),
    ]

    operations = [
    ]
