# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-13 08:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0023_auto_20180828_0917'),
        ('fleet_management', '0101_merge_20190130_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='claim_settlement_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Claim Settlement Date'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='date_claim_registered',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date Claim Registered'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='date_excess',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date Excess Paid'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='date_for_repair',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date In For Repairs'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='date_reported_to_fleet',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date Reported to Fleet'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='date_reported_to_insurance',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Date Reported to Insurance'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='excess_amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Excess Amount'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='insurance_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='released_from_repairs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Released from Repairs'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='repair_quote_amount',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Repairs Quote Amount'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='repair_quote_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Repairs Quote Date'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='repair_quote_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Repair Quote Number'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='repair_vendor',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_repair_vendor', to='operations.Vendor', verbose_name=b'Repairs Service Provider'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='time_of_accident',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Time of Accident'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='towing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Towing Date'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='towing_quote_amount',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Towing Quote Amount'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='towing_quote_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Towing Quote Number'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='towing_vendor',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_towing_vendor', to='operations.Vendor', verbose_name=b'Towing Service Provider'),
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='vehicle_tracking',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Vehicle Tracking'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='claim_type',
            field=models.CharField(blank=True, choices=[(b'accident claim', b'Accident Claim'), (b'vehicle theft', b'Vehicle Theft'), (b'windscreen', b'Windscreen'), (b'other', b'Other')], max_length=50, null=True, verbose_name=b'Claim Type'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='damage_description',
            field=models.TextField(blank=True, null=True, verbose_name=b'Damage Description'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='incident_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Incident Date'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='incident_description',
            field=models.TextField(blank=True, null=True, verbose_name=b'Incident Description'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='insurance_reference_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Claim Reference'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
