# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0101_merge_20190130_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicletyre',
            name='replacement_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Replacement Date'),
        ),
        migrations.AddField(
            model_name='vehicletyre',
            name='replacement_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Replacement Date'),
        ),
        migrations.AlterField(
            model_name='historicalvehicletyre',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Manufacture Date'),
        ),
        migrations.AlterField(
            model_name='historicalvehicletyre',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Size'),
        ),
        migrations.AlterField(
            model_name='vehicletyre',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Manufacture Date'),
        ),
        migrations.AlterField(
            model_name='vehicletyre',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Size'),
        ),
    ]
