# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0101_merge_20190130_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcard',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Cancel Reason'),
        ),
        migrations.AddField(
            model_name='historicalfuelcard',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Cancel Reason'),
        ),
    ]
