# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-12 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0102_auto_20190227_1342'),
        ('fleet_management', '0102_auto_20190222_1559'),
    ]

    operations = [
    ]
