# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-13 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0102_auto_20190313_1001'),
        ('fleet_management', '0103_merge_20190312_1315'),
    ]

    operations = [
    ]
