# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 13:47
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0018_auto_20180719_0756'),
        ('facilities', '0002_auto_20180727_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('reference', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[(b'allocated', b'Allocated'), (b'received', b'Received')], max_length=255)),
                ('opening_stock', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Opening Stock')),
                ('quantity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name=b'Quantity')),
                ('transaction_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Transaction Date')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_stock_received', to=settings.AUTH_USER_MODEL)),
                ('district', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='district_stock_allocation', to='operations.Branch')),
                ('modified_by', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_stock_received', to=settings.AUTH_USER_MODEL)),
                ('stock_item', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_item_stock_recieved', to='facilities.StockItem', verbose_name=b'Stock Item')),
                ('supplier', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_stock_received', to='operations.Vendor')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='stockallocated',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockallocated',
            name='district',
        ),
        migrations.RemoveField(
            model_name='stockallocated',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='stockallocated',
            name='stock_item',
        ),
        migrations.RemoveField(
            model_name='stockreceived',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockreceived',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='stockreceived',
            name='stock_item',
        ),
        migrations.RemoveField(
            model_name='stockreceived',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='StockAllocated',
        ),
        migrations.DeleteModel(
            name='StockReceived',
        ),
    ]
