# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLicence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('licence_number', models.CharField(max_length=120)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('code', models.CharField(blank=True, choices=[('A', 'A-Motor Cycle'), ('A1', 'A1-Motor Cycle LTE 125cc'), ('B', 'B-Light Motor Vehicle LTE 3500kg'), ('EB', 'EB-Articulated vehicles LTE 3500kg'), ('C1', 'C1-Minibuses, Buses and Goods vehicles LTE 16000kg'), ('C', 'C-Buses and goods vehicles GTE 16000kg'), ('EC1', 'EC1-Articulated vehicles LTE 16000kg'), ('EC', 'EC-Articulated vehicles GTE 18000kg')], default=None, max_length=120, null=True)),
                ('vehicle_restrictions', models.CharField(blank=True, choices=[('no_restrictions', 'No Restrictions'), ('automatic', 'Automatic transmission'), ('electric', 'Electrically powered'), ('physically_disabled', 'Physically disabled'), ('bus', 'Bus GTE 16000kg (GVM) permited')], default=None, max_length=120, null=True)),
                ('driver_restrictions', models.CharField(blank=True, choices=[('no_restrictions', 'No Restrictions'), ('glasses', 'Glasses or Contact lenses'), ('artificial_limb', 'Artificial limb')], default=None, max_length=120, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('employee_no', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('commission_code', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('id_number', models.CharField(max_length=120)),
                ('email', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('role', models.CharField(blank=True, choices=[('RM', 'Regional Manager'), ('RSM', 'Regoinal Sales Manager'), ('PAM', 'Regional Admin Manager'), ('BM', 'Branch Manager'), ('DM', 'Junior District Manager'), ('SM', 'Sales Manager'), ('SADM', 'Executive Agent'), ('ADM', 'Assistant District Manager'), ('AG', 'Agent')], max_length=20, null=True)),
                ('division', models.CharField(blank=True, choices=[('marketing', 'Marketing'), ('sales', 'Sales'), ('other', 'Other')], max_length=20, null=True)),
                ('imported', models.BooleanField(default=False)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalDrivingLicence',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('changed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('licence_number', models.CharField(max_length=120)),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('code', models.CharField(blank=True, choices=[('A', 'A-Motor Cycle'), ('A1', 'A1-Motor Cycle LTE 125cc'), ('B', 'B-Light Motor Vehicle LTE 3500kg'), ('EB', 'EB-Articulated vehicles LTE 3500kg'), ('C1', 'C1-Minibuses, Buses and Goods vehicles LTE 16000kg'), ('C', 'C-Buses and goods vehicles GTE 16000kg'), ('EC1', 'EC1-Articulated vehicles LTE 16000kg'), ('EC', 'EC-Articulated vehicles GTE 18000kg')], default=None, max_length=120, null=True)),
                ('vehicle_restrictions', models.CharField(blank=True, choices=[('no_restrictions', 'No Restrictions'), ('automatic', 'Automatic transmission'), ('electric', 'Electrically powered'), ('physically_disabled', 'Physically disabled'), ('bus', 'Bus GTE 16000kg (GVM) permited')], default=None, max_length=120, null=True)),
                ('driver_restrictions', models.CharField(blank=True, choices=[('no_restrictions', 'No Restrictions'), ('glasses', 'Glasses or Contact lenses'), ('artificial_limb', 'Artificial limb')], default=None, max_length=120, null=True)),
                ('date_added', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical driving licence',
            },
        ),
    ]
