# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:32
from __future__ import unicode_literals

from django.db import migrations

def create_sample_employees(apps, schema):
    from django.core.management import call_command
    call_command('create_sample_employees')


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20171206_1331'),
    ]

    operations = [
        migrations.RunPython(create_sample_employees)
    ]
