# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20171206_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='commission_code',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Commission Code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_no',
            field=models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Employee Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=120, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(max_length=120, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=120, verbose_name='Last Name'),
        ),
    ]
