# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 14:47
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20180205_1624'),
        ('employees', '0004_auto_20180105_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='region',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees_in_region', to='operations.Region'),
        ),
    ]
