# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20180205_1624'),
        ('employees', '0005_employee_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivinglicence',
            name='licence_image',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.Document'),
        ),
        migrations.AddField(
            model_name='historicaldrivinglicence',
            name='licence_image',
            field=lib.fields.ProtectedForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='operations.Document'),
        ),
        migrations.AlterField(
            model_name='drivinglicence',
            name='code',
            field=models.CharField(blank=True, choices=[('A', 'A-Motor Cycle'), ('A1', 'A1-Motor Cycle LTE 125cc'), ('B', 'B-Light Motor Vehicle LTE 3500kg'), ('EB', 'EB-Articulated vehicles LTE 3500kg'), ('C1', 'C1-Minibuses, Buses and Goods vehicles LTE 16000kg'), ('C', 'C-Buses and goods vehicles GTE 16000kg'), ('EC1', 'EC1-Articulated vehicles LTE 16000kg'), ('EC', 'EC-Articulated vehicles GTE 18000kg')], default='B', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='drivinglicence',
            name='driver_restrictions',
            field=models.CharField(blank=True, choices=[('no_restrictions', 'No Restrictions'), ('glasses', 'Glasses or Contact lenses'), ('artificial_limb', 'Artificial limb')], default='no_restrictions', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='drivinglicence',
            name='vehicle_restrictions',
            field=models.CharField(blank=True, choices=[('no_restrictions', 'No Restrictions'), ('automatic', 'Automatic transmission'), ('electric', 'Electrically powered'), ('physically_disabled', 'Physically disabled'), ('bus', 'Bus GTE 16000kg (GVM) permited')], default='no_restrictions', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldrivinglicence',
            name='code',
            field=models.CharField(blank=True, choices=[('A', 'A-Motor Cycle'), ('A1', 'A1-Motor Cycle LTE 125cc'), ('B', 'B-Light Motor Vehicle LTE 3500kg'), ('EB', 'EB-Articulated vehicles LTE 3500kg'), ('C1', 'C1-Minibuses, Buses and Goods vehicles LTE 16000kg'), ('C', 'C-Buses and goods vehicles GTE 16000kg'), ('EC1', 'EC1-Articulated vehicles LTE 16000kg'), ('EC', 'EC-Articulated vehicles GTE 18000kg')], default='B', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldrivinglicence',
            name='driver_restrictions',
            field=models.CharField(blank=True, choices=[('no_restrictions', 'No Restrictions'), ('glasses', 'Glasses or Contact lenses'), ('artificial_limb', 'Artificial limb')], default='no_restrictions', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldrivinglicence',
            name='vehicle_restrictions',
            field=models.CharField(blank=True, choices=[('no_restrictions', 'No Restrictions'), ('automatic', 'Automatic transmission'), ('electric', 'Electrically powered'), ('physically_disabled', 'Physically disabled'), ('bus', 'Bus GTE 16000kg (GVM) permited')], default='no_restrictions', max_length=120, null=True),
        ),
    ]
