# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-20 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20180206_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicence',
            name='code',
            field=models.CharField(blank=True, choices=[('A', 'A-Motor Cycle'), ('A1', 'A1-Motor Cycle LTE 125cc'), ('AA', 'AA-International Driving Permit'), ('B', 'B-Light Motor Vehicle LTE 3500kg'), ('EB', 'EB-Articulated vehicles LTE 3500kg'), ('C1', 'C1-Minibuses, Buses and Goods vehicles LTE 16000kg'), ('C', 'C-Buses and goods vehicles GTE 16000kg'), ('EC1', 'EC1-Articulated vehicles LTE 16000kg'), ('EC', 'EC-Articulated vehicles GTE 18000kg')], default='B', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldrivinglicence',
            name='code',
            field=models.CharField(blank=True, choices=[('A', 'A-Motor Cycle'), ('A1', 'A1-Motor Cycle LTE 125cc'), ('AA', 'AA-International Driving Permit'), ('B', 'B-Light Motor Vehicle LTE 3500kg'), ('EB', 'EB-Articulated vehicles LTE 3500kg'), ('C1', 'C1-Minibuses, Buses and Goods vehicles LTE 16000kg'), ('C', 'C-Buses and goods vehicles GTE 16000kg'), ('EC1', 'EC1-Articulated vehicles LTE 16000kg'), ('EC', 'EC-Articulated vehicles GTE 18000kg')], default='B', max_length=120, null=True),
        ),
    ]
