# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-28 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20180720_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cell_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
