# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20171206_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='doc_file',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='doc_name',
            new_name='document_name',
        ),
    ]
