# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-03 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20171206_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
