# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_document_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(max_length=255, verbose_name=b'Address Line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Address Line 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Postal Code'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cell_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name=b'Cell Number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name=b'Contact First Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Contact Last Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tel_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Telephone Number'),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='name',
            field=models.CharField(max_length=255, verbose_name=b'Insurer Name'),
        ),
    ]
