# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20180205_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseticket',
            name='technician',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baseticket_technician', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='baseticket',
            name='created_by',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='baseticket_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
