# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_auto_20180206_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name=b'Service Provider')),
                ('address', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_provider_address', to='operations.Address')),
                ('contact_person', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_provider_contact', to='operations.Contact')),
                ('created_by', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_provider', to=settings.AUTH_USER_MODEL)),
                ('modified_by', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_service_provider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
