# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name=b'Vendor')),
                ('vendor_type', models.CharField(choices=[(b'branding', b'Branding'), (b'dealer', b'Dealer'), (b'installer', b'Installer'), (b'insurance', b'Insurance'), (b'service provider', b'Service Provider'), (b'tracker', b'Tracker')], db_index=True, max_length=50, verbose_name=b'Vendor Type')),
                ('address', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_address', to='operations.Address')),
                ('contact_person', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_contact', to='operations.Contact')),
                ('created_by', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_vendor', to=settings.AUTH_USER_MODEL)),
                ('modified_by', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
