# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseticket',
            name='category',
            field=models.CharField(choices=[(b'fleet management', b'Fleet Management'), (b'inventory', b'Inventory'), (b'property and facilities', b'Property & Facilities'), (b'offices', b'Offices')], db_index=True, default=b'new', max_length=50),
        ),
        migrations.AddField(
            model_name='baseticket',
            name='subject',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baseticket',
            name='status',
            field=models.CharField(choices=[(b'new', b'New'), (b'pending', b'Pending'), (b'closed', b'Closed')], db_index=True, default=b'new', max_length=50),
        ),
    ]
