# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 07:43
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_auto_20180517_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='region',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='branch_region', to='operations.Region'),
        ),
    ]
