# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 11:45
from __future__ import unicode_literals

from django.db import migrations
from fleet_management.models import Incident

class Migration(migrations.Migration):

    def assign_incident_vehicle(apps, schema_editor):
        incidents = Incident.objects.all()

        for incident in incidents:
            if incident.vehicle_driver:
                incident.vehicle = incident.vehicle_driver.vehicle
                incident.save()

    dependencies = [
        ('operations', '0015_branch_region'),
    ]

    operations = [
        migrations.RunPython(assign_incident_vehicle)
    ]
