# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-19 05:56
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_auto_20180703_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsuser',
            name='district',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_district', to='operations.Branch'),
        ),
        migrations.AddField(
            model_name='operationsuser',
            name='region',
            field=lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_region', to='operations.Region'),
        ),
    ]
