# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-27 14:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_auto_20180822_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('bank_name', models.CharField(choices=[(b'', b'Please select'), (b'ABSA', b'ABSA'), (b'AFRICAN', b'AFRICAN'), (b'ALBARAKA', b'ALBARAKA'), (b'ATHENS', b'ATHENS'), (b'BIDVEST', b'BIDVEST'), (b'BOE', b'BOE'), (b'CAPITEC', b'CAPITEC'), (b'CITI', b'CITI'), (b'FBC', b'FBC'), (b'FINBOND', b'FINBOND'), (b'FNB', b'FNB'), (b'FNBBOTS', b'FNBBOTS'), (b'FNBLES', b'FNBLES'), (b'FNBNAM', b'FNBNAM'), (b'FNBSWAZ', b'FNBSWAZ'), (b'FNBTRANS', b'FNBTRANS'), (b'GRINDROD', b'GRINDROD'), (b'HABIB', b'HABIB'), (b'HBZ', b'HBZ'), (b'HSBC', b'HSBC'), (b'INDIA', b'INDIA'), (b'INVESTEC', b'INVESTEC'), (b'ITHALA', b'ITHALA'), (b'JPMORGAN', b'JPMORGAN'), (b'MERCANT', b'MERCANT'), (b'MTN', b'MTN'), (b'NBS', b'NBS'), (b'NEDBANK', b'NEDBANK'), (b'NEDBOND', b'NEDBOND'), (b'NEDLES', b'NEDLES'), (b'NEDNAM', b'NEDNAM'), (b'NEDSWAZ', b'NEDSWAZ'), (b'OLYMPUS', b'OLYMPUS'), (b'PARIBAS', b'PARIBAS'), (b'PEOP CUR', b'PEOP CUR'), (b'PEOPLES', b'PEOPLES'), (b'PEP', b'PEP'), (b'POST', b'POST'), (b'ROYALSCO', b'ROYALSCO'), (b'SASFIN', b'SASFIN'), (b'STANCHAR', b'STANCHAR'), (b'STANDARD', b'STANDARD'), (b'STANNAM', b'STANNAM'), (b'STANSWAZ', b'STANSWAZ'), (b'STD LES', b'STD LES'), (b'UBANK', b'UBANK'), (b'UNIBANK', b'UNIBANK'), (b'VBSMut', b'VBSMut'), (b'WINDHOEK', b'WINDHOEK')], db_index=True, max_length=255, verbose_name=b'Bank Name')),
                ('branch_code', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Branch Code')),
                ('account_holder_name', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Account Holder Name')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name=b'Account Number')),
                ('created_by', lib.fields.ProtectedForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_provider_bank', to=settings.AUTH_USER_MODEL)),
                ('modified_by', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modified_service_provider_bank', to=settings.AUTH_USER_MODEL)),
                ('vendor', lib.fields.ProtectedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bank_details', to='operations.Vendor')),
            ],
            options={
                'default_permissions': [],
                'abstract': False,
            },
        ),
    ]
