# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_vendorbankdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbankdetail',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name=b'Account Holder Name'),
        ),
    ]
